name: C-STEM
favicon: null
layout_spectrum: 0.7507
typography_spectrum: 0.27271
title: C-STEM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000200'
    - '#fefefe'
    - '#6e706d'
    - '#aeb2b1'
    - '#e05a11'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
